Configure new environment with pipenv
rarygc/weather-buddy-api pull request #4
Opened 2021-04-09 13:05 UTC by rarygc

This PR configure the python environment to use `pipenv` as environment package manager, while remove `requirements.txt` file and your usage.

The files `Pipfile` and `Pipfile.lock` has been created and will be used to manage the project's dependencies.

2021-04-09 16:10 UTC, dluiscosta requested changes

2021-04-09 16:10 UTC, dluiscosta commented on Pipfile
> +Werkzeug = "==1.0.1"
The `Pipfile` should contain only the dependencies which your application directly uses, and not it's further dependencies, since one of it's jobs is to dynamically determine them and their versions, solving potential conflicts between multiple direct dependencies that further require a same third dependency.

2021-04-09 16:10 UTC, dluiscosta commented on Pipfile
> +pytest = "==6.2.2"
pytest, for example, doesn't need to be installed in the production environment, as it is a test dependency. In Pipfile's nomenclature, it is a dev-package, which [includes both development and test dependencies](https://github.com/pypa/pipenv/issues/1327#issuecomment-359849719).

To fix this, you can use the `[dev-packages]` section of this INI file.

2021-04-09 16:10 UTC, dluiscosta commented on Pipfile
> +Werkzeug = "==1.0.1"
It is important to not let your dependency versions unbounded, but pinning them completely also prevent error fixes that were made upstream to reach your application, as well as performance improvements. 

Fortunately, though, we can rely on [semantic versioning](https://semver.org/) to ensure that only backward compatible changes can implicitly come downstream. In fact, pipenv's main documentation has a good recommendation about this.

2021-04-09 20:35 UTC, rarygc commented
Taking into consideration the suggestions mentioned, the following improvements have been made to package management:

1. The Pipfile is separating dev dependencies from prod dependencies, like this:
```toml
[packages]
flask = "~=1.1"

[dev-packages]
pytest = "~=6.2"
```

2. The version of packages is following the best practices of the control version, recommend by **[Pipenv documentation](https://pipenv.pypa.io/en/latest/basics/#specifying-versions-of-a-package)** and **[SemVer 2.0](https://semver.org)**, like this:
```toml
flask = "~=1.1"
```

3. The Secondary packages has been removed from Pipfile and only the application's primary packages are being referenced as dependencies.

2021-04-12 00:53 UTC, dluiscosta commented
Awesome, well done.

2021-04-12 00:54 UTC, dluiscosta approved these changes

2021-04-12 10:49 UTC, merged